### ISSUE TITLE
Doesn't work for debug mode

### ISSUE THREAD

**Issue by MIyulong** [thekevinbrown/react-native-schemes-manager#54] opened 2018-12-19 03:18 UTC
it's my package.json, i run 'yarn install' and get successful,  but i still not able to work in debug model with my react-native project
![image](https://user-images.githubusercontent.com/8175565/50196714-37003080-037f-11e9-9024-65aa33ab47bb.png)
![image](https://user-images.githubusercontent.com/8175565/50196834-c1e12b00-037f-11e9-8373-0287b425ec8d.png)
![image](https://user-images.githubusercontent.com/8175565/50196844-cdcced00-037f-11e9-830d-aab4ce175573.png)

**Comment by thekevinbrown** [comment] 2019-01-20 23:51
Hi @MIyulong,

I'm unable to reproduce on my side, so I'll go ahead and close this issue for now. If you can provide a reproduction case please open a new issue and I'd be happy to have a look at what's going on.

**Closed by thekevinbrown** 2019-01-20 23:52 UTC
