### ISSUE TITLE
hide-library-schemes has no effect

### ISSUE THREAD

**Issue by mlostekk** [thekevinbrown/react-native-schemes-manager#58] opened 2019-02-08 10:29 UTC
Environment 
Xcode 10.1
Node v8.15.0 (via NVM 0.33.5)
macOS Mojave
10.14.2 (18C54)

### Steps to reproduce the behavior
run `react-native-schemes-manager hide-library-schemes`
see output 

### Expected behavior
run `react-native-schemes-manager hide-library-schemes`
see less library schemes

### Actual behavior
![bildschirmfoto 2019-02-08 um 11 27 46](https://user-images.githubusercontent.com/10534316/52472854-a848ac80-2b94-11e9-95fa-ff1cbda1740a.jpg)

**Comment by thekevinbrown** [comment] 2019-02-15 05:18
If you watch the changes to the project files, they should still be made. Usually XCode won't actually update visually until you close it and re-open it.

So try these steps and let me know if it solves your problem:

1. Completely quit XCode
2. Run the `all` command
3. Open the project in XCode again

If that doesn't help, please provide the terminal output of running the `all` command so I can have a crack at seeing what's going on.

**Comment by thekevinbrown** [comment] 2019-02-27 05:13
I'll go ahead and assume this resolved the issue for you. If not, please let me know, happy to help!

**Comment by mlostekk** [comment] 2019-02-27 09:08
Well, it does not have any effect on my side. Tried everything from deleting derivedata folders, to clearing caches, to full git clone of the project. I will try to reproduce it on a small / fresh project and post the link to the repo

**Comment by kg-currenxie** [comment] 2019-08-01 07:38
Same here. No effect. Closed Xcode before runnnig.
RN 59.10

**Comment by thekevinbrown** [comment] 2019-08-01 07:42
@kg-currenxie or @mlostekk are either of you able to provide a reproduction case? I can't replicate this.

**Comment by kg-currenxie** [comment] 2019-08-01 07:45
I'll try this weekend :)

**Comment by richeterre** [comment] 2019-08-02 19:15
@kg-currenxie I'd be curious to hear about your findings, because I'm seeing the same issue – the command has no effect whatsoever for me.

**Comment by kg-currenxie** [comment] 2019-08-03 16:25
Here's my test repo: https://github.com/kg-currenxie/schemas-test-react-native
1. `yarn`
2. `react-native-link`
3. Check XCode, all schemas visible
4. `yarn run fix-code` (runs `react-native-schemes-manager hide-library-schemes`)
5. Schemas still visible

Note; I'm using custom schemas, and not a default RN-project one (`Debug`).
![Screenshot 2019-08-04 at 00 24 30](https://user-images.githubusercontent.com/48229166/62414462-42724480-b64e-11e9-8a80-1e9bddea06e3.png)

**Comment by marcferna** [comment] 2019-08-12 22:46
Do the schemes you want to change end in `.xcscheme_^#shared#^_`?

**Comment by kg-currenxie** [comment] 2020-01-09 02:50
The project got on-hold, and recently picked up.
Now using RN 0.61.x and suddenly it works fine. Not sure why 🤷‍♂ but the it's not an issue for me anymore :)

**Closed** 2023-10-11 05:26 UTC
